openapi: 3.0.1
info:
  title: Folder Fetch API
  description: API that returns folder list for a given user
  version: "1.0"
servers:
  - url: https://<your-choreo-domain>/folder-fetch-api
paths:
  /folders:
    get:
      summary: Get folder list for a user
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
          description: The username to fetch folders for.
      responses:
        "200":
          description: A JSON array of folder names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - "project A"
                - "project B"
