openapi: 3.0.1
info:
  title: Folder Fetch API
  description: A REST API that returns a hard-coded folder list based on the provided username.
  version: "1.0"
servers:
  - url: https://<your-choreo-domain>/folder-fetch-api/v1.0
paths:
  /:
    get:
      summary: Get Folder List
      description: Returns a folder list for the provided username. If no username is provided, returns an empty array.
      operationId: getFolderList
      parameters:
        - in: query
          name: username
          required: false
          schema:
            type: string
          description: The username for which to fetch the folder list.
      responses:
        '200':
          description: A JSON array of folder names.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ["project A", "project B"]
